name: rileymaclean
favicon: null
layout_spectrum: 0.5126747840549797
typography_spectrum: 0.9509441899135709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e3e1e2'
    - '#252019'
    - '#aba4a2'
    - '#675d5a'
  brandStrength: 0.8125
  lightness: 0.3604833635035902
  saturation: 0.375
  rhythmicContrast: 0.6892868534196168
purpose: []
