name: rileymaclean
favicon: null
layout_spectrum: 0.5126747840549797
typography_spectrum: 0.9509441899135709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d4d1'
    - '#000000'
    - '#748a90'
    - '#1d4207'
    - '#90c14e'
  brandStrength: 0.875
  lightness: 0.3604833635035902
  saturation: 0.5
  rhythmicContrast: 0.6892868534196168
purpose: []
